increase retention days to a year
OpenCyphal/yakut pull request #111
Opened 2024-07-26 15:57 UTC by songmeo

increase retention days of Yakut test to a year

![image](https://github.com/user-attachments/assets/e59c22fa-d04d-402a-8ce5-bd8f04545dfd)

2024-07-27 07:09 UTC, maksimdrachov approved these changes
The tests failing indeed has nothing to do with this change.

2024-07-31 09:33 UTC, pavel-kirienko requested changes

2024-07-31 09:33 UTC, pavel-kirienko commented on .github/workflows/test-and-release.yml
> +          retention-days: 365
The maximum is 90 days

```suggestion
          retention-days: 90
```

![image](https://github.com/user-attachments/assets/99ebf9e0-6654-4684-b99b-54a679e2ab2d)

2024-08-30 10:40 UTC, maksimdrachov commented
@pavel-kirienko Merge this?

2024-08-30 14:06 UTC, pavel-kirienko commented
@maksimdrachov please pull it into your https://github.com/OpenCyphal/yakut/pull/109, then close it.

2025-05-12 15:31 UTC, pavel-kirienko commented
merged into dev

2025-05-12 15:31 UTC, closed without merging